Repository m3ntorship/pickify-frontend, pull requests merged in 2021-07, with the labels that each got.

#251 Voting stats component
  modules/shared/components/atoms/Slider/ISlider.d.ts
  modules/shared/components/atoms/Slider/Slider.module.css
  modules/shared/components/atoms/Slider/Slider.stories.tsx
  modules/shared/components/atoms/Slider/Slider.test.tsx
  modules/shared/components/atoms/Slider/Slider.tsx
  modules/shared/components/atoms/Slider/__snapshots__/Slider.test.tsx.snap
  modules/shared/components/molecules/ImagePollUncovored/ImagePollUncovored.module.css
  modules/shared/components/molecules/ImagePollUncovored/ImagePollUncovored.stories.tsx
  modules/shared/components/molecules/ImagePollUncovored/ImagePollUncovored.test.tsx
  modules/shared/components/molecules/ImagePollUncovored/ImagePollUncovored.tsx
  modules/shared/components/molecules/ImagePollUncovored/__snapshots__/ImagePollUncovored.test.tsx.snap
  modules/shared/components/molecules/ImagePollUncovored/types/IImagePollUncovored.d.ts
  tailwind.config.js
Labels: ready-for-review

#254 transform one option from options to group
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
Labels: ready-for-review

#256 added a custom hook to detect click outside
  modules/shared/hooks/useDetectClickOut/IUseDetectClickOut.d.ts
  modules/shared/hooks/useDetectClickOut/useDetectClickOut.ts
Labels: ready-for-review

#244 Delete post
  modules/HomePage/components/Posts.tsx
  modules/shared/components/atoms/DropDown/DropDown.module.css
  modules/shared/components/atoms/DropDown/DropDown.stories.tsx
  modules/shared/components/atoms/DropDown/DropDown.test.tsx
  modules/shared/components/atoms/DropDown/DropDown.tsx
  modules/shared/components/atoms/DropDown/IDropDown.d.ts
  modules/shared/components/atoms/DropDown/__snapshots__/DropDown.test.tsx.snap
  modules/shared/components/atoms/DropDown/mockedOptions.ts
  modules/shared/components/molecules/PostViewHeader/IPostViewHeader.d.ts
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.test.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/organisms/ImagePollView/IImagePollView.d.ts
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/MiniSurveyView/IMiniSurveyView.d.ts
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.test.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/ITextPollView.d.ts
  modules/shared/components/organisms/TextPollView/TextPollView.test.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
Labels: ready-for-review

#195 the first creation of the post modal component
  modules/HomePage/components/NewPost/NewPost.module.css
  modules/HomePage/components/NewPost/NewPost.test.tsx
  modules/HomePage/components/NewPost/NewPost.tsx
  modules/HomePage/pages/home-page.module.css
  modules/HomePage/pages/home-page.tsx
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.tsx
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.module.css
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/components/organisms/Modal/IModal.d.ts
  modules/shared/components/organisms/Modal/Modal.module.css
  modules/shared/components/organisms/Modal/Modal.stories.tsx
  modules/shared/components/organisms/Modal/Modal.test.tsx
  modules/shared/components/organisms/Modal/Modal.tsx
  modules/shared/components/organisms/Modal/__snapshots__/Modal.test.tsx.snap
  modules/shared/components/organisms/PostCreation/PostCreation.stories.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  modules/shared/components/organisms/PostCreation/types/IPostCreation.d.ts
  modules/shared/components/organisms/TextPollCreation/TextPollCreation.tsx
  package.json
  pages/_document.tsx
  tailwind.config.js
  yarn.lock
Labels: ready-for-review

#258 Create symbol generator
  modules/shared/components/molecules/Option/Option.tsx
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/logic/symbolGenerator/symbolGenerator.ts
Labels: ready-for-review

#259 Configuration file
  modules/shared/components/atoms/FileUploader/FileUploader.stories.tsx
  modules/shared/components/atoms/FileUploader/FileUploader.test.tsx
  modules/shared/components/molecules/Misc/Misc.stories.tsx
  modules/shared/components/molecules/Misc/Misc.test.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.test.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.test.tsx
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/configuration/ConfigPostCreation/config.ts
  modules/shared/hooks/useUploadedFiles/useUploadedFiles.test.tsx
  modules/shared/hooks/useUploadedFiles/useUploadedFiles.ts
Labels: ready-for-review

#264 Enhance image poll styles & error handling
  modules/shared/components/atoms/DropDown/DropDown.module.css
  modules/shared/components/atoms/DropDown/DropDown.stories.tsx
  modules/shared/components/atoms/DropDown/DropDown.test.tsx
  modules/shared/components/atoms/DropDown/DropDown.tsx
  modules/shared/components/atoms/DropDown/IDropDown.d.ts
  modules/shared/components/atoms/DropDown/__snapshots__/DropDown.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.stories.tsx
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/IImagePollOption.d.ts
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.stories.tsx
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.test.tsx
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/ImagePollUncovered/ImagePollUncovered.stories.tsx
  modules/shared/components/molecules/ImagePollUncovered/ImagePollUncovered.test.tsx
  modules/shared/components/molecules/ImagePollUncovered/ImagePollUncovered.tsx
  modules/shared/components/molecules/ImagePollUncovered/__snapshots__/ImagePollUncovered.test.tsx.snap
  modules/shared/components/molecules/ImagePollUncovered/types/IImagePollUncovered.d.ts
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/SignleImagePollOption/ISignleImagePollOption.d.ts
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.stories.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.test.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.tsx
  modules/shared/components/molecules/SignleImagePollOption/__snapshots__/SignleImagePollOption.test.tsx.snap
  modules/shared/components/molecules/UploadingImage/UploadingImage.module.css
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
Labels: ready-for-review

#270 displayed the mini survey image if there's url in the media
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
Labels: ready-for-review

#280 make the page refresh after every sign in #277
  modules/shared/logic/userId/userId.ts
Labels: ready-for-merge

#282 Option group limit
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupWrapper.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.test.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.tsx
Labels: ready-for-merge

#281 Enhanced delete api function
  modules/HomePage/api/DeletePostApi/IPostsApi.d.ts
  modules/HomePage/api/DeletePostApi/deletePostsApi.ts
  modules/HomePage/components/Posts.tsx
Labels: ready-for-review

#291 Transform posts media
  modules/HomePage/components/Posts/Posts.tsx
  modules/HomePage/components/Posts/PostsHelpers.ts
  modules/HomePage/pages/home-page.tsx
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.stories.tsx
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.stories.tsx
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.test.tsx
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.stories.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.test.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
Labels: ready-for-review

#302 update post results
  modules/HomePage/api/votesApi/IvotesApi.d.ts
  modules/HomePage/api/votesApi/voteApi.test.ts
  modules/HomePage/api/votesApi/votesHelpers.ts
  modules/HomePage/components/Posts/Posts.tsx
  modules/HomePage/components/Posts/PostsHelpers.ts
  modules/shared/api/getPosts.api.ts
  modules/shared/api/postsApi.api.ts
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.stories.tsx
  modules/shared/components/molecules/ImagePollGroup/data.ts
  modules/shared/components/molecules/MiniSurveyViewOptions/IMiniSurveyViewOptions.d.ts
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.test.tsx
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.tsx
  modules/shared/components/molecules/MiniSurveyViewOptions/data.ts
  modules/shared/components/molecules/OptionGroupView/IOptionGroupView.d.ts
  modules/shared/components/molecules/OptionGroupView/OptionGroupView.tsx
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.stories.tsx
  modules/shared/components/molecules/TextPollViewOptions/ITextPollViewOptions.d.ts
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.test.tsx
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.tsx
  modules/shared/components/molecules/TextPollViewOptions/data.ts
  modules/shared/components/organisms/ImagePollView/ImagePollView.stories.tsx
  modules/shared/components/organisms/MiniSurveyView/IMiniSurveyView.d.ts
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.stories.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.test.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/TextPollView/ITextPollView.d.ts
  modules/shared/components/organisms/TextPollView/TextPollView.stories.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.test.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/logic/userId/userId.ts
  modules/shared/logic/votesLogic/votesLogic.test.ts
  modules/shared/types/postFeed/IPostFeed.d.ts
  pages/index.tsx
Labels: ready-for-review, under review

#308 User error handling
  modules/shared/components/molecules/UserInfo/UserInfo.test.tsx
  modules/shared/components/molecules/UserInfo/UserInfo.tsx
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/types/postFeed/IPostFeed.d.ts
Labels: ready-for-review

#310 hide the caption if no text is available
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.tsx
Labels: ready-for-review

#309 enhance dropdown menu for creation
  modules/shared/components/atoms/DropDown/mockedOptions.ts
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
Labels: ready-for-review

#311 enhanced and added the mini survey total votes
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
Labels: ready-for-review

#315 make mini-survey image optional
  modules/shared/components/atoms/FileUploader/FileUploader.tsx
  modules/shared/components/atoms/FileUploader/IFileUploader.d.ts
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
Labels: ready-for-review

#297 Created UploadingImage Story
  modules/shared/components/molecules/UploadingImage/UploadingImage.stories.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/molecules/UploadingImage/ricardo-henri-W7Fc-k3IpmU-unsplash.jpg
Labels: ready-for-review

#316 detect text direction
  modules/shared/components/atoms/TextInputs/TextInput.tsx
  modules/shared/components/atoms/TextInputs/__snapshots__/TextInput.test.tsx.snap
  modules/shared/components/atoms/TextOptionViewCovered/TextOptionViewCovered.tsx
  modules/shared/components/atoms/TextOptionViewCovered/__snapshots__/TextOptionViewCovered.test.tsx.snap
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/__snapshots__/TextOptionViewUncovered.test.tsx.snap
  modules/shared/components/molecules/ImageCaption/ImageCaption.tsx
  modules/shared/components/molecules/ImageCaption/__snapshots__/ImageCaption.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/MiniSurveyViewOptions/__snapshots__/MiniSurveyViewOptions.test.tsx.snap
  modules/shared/components/molecules/SignleImagePollOption/__snapshots__/SignleImagePollOption.test.tsx.snap
  modules/shared/components/molecules/SignleImagePollOption/mockedOptions.ts
  modules/shared/components/molecules/TextPollViewOptions/__snapshots__/TextPollViewOptions.test.tsx.snap
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
Labels: ready-for-merge

#317 make File Uploader for Mini Survey accepts only one image
  modules/shared/components/atoms/FileUploader/FileUploader.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/configuration/ConfigPostCreation/config.ts
Labels: ready-for-review

#290 added feature flag initial functionality
  modules/shared/configuration/FeatureFlag/Feature.tsx
  modules/shared/configuration/FeatureFlag/FeatureFlagConfig.ts
Labels: ready-for-review

#321 Status code enhancements
  modules/HomePage/api/DeletePostApi/deletePostHelpers.ts
  modules/HomePage/api/DeletePostApi/deletePosts.test.ts
  modules/HomePage/api/DeletePostApi/deletePostsApi.ts
  modules/HomePage/api/votesApi/voteApi.ts
  modules/HomePage/api/votesApi/votesHelpers.ts
  modules/shared/api/EStatusCode.ts
  modules/shared/logic/generateErrMsg/generateErrMsg.test.ts
  modules/shared/logic/generateErrMsg/generateErrMsg.ts
Labels: ready-for-review

#323 Enhance mini survey
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.test.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.tsx
Labels: ready-for-review

#319 Image view component
  modules/shared/components/atoms/ImageView/IImageView.d.ts
  modules/shared/components/atoms/ImageView/ImageView.module.css
  modules/shared/components/atoms/ImageView/ImageView.stories.tsx
  modules/shared/components/atoms/ImageView/ImageView.test.tsx
  modules/shared/components/atoms/ImageView/ImageView.tsx
  modules/shared/components/atoms/ImageView/__snapshots__/ImageView.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/SignleImagePollOption/SignleImagePollOption.tsx
  modules/shared/components/molecules/SignleImagePollOption/__snapshots__/SignleImagePollOption.test.tsx.snap
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
Labels: ready-for-merge

#294 Modified maximum image size
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
Labels: ready-for-review

#324 changed misc component to to more descriptive name
  modules/shared/components/icons/errorIcon.svg
  modules/shared/components/icons/successIcon.svg
  modules/shared/components/molecules/MessageBox/MessageBox.module.css
  modules/shared/components/molecules/MessageBox/MessageBox.stories.tsx
  modules/shared/components/molecules/MessageBox/MessageBox.test.tsx
  modules/shared/components/molecules/MessageBox/MessageBox.tsx
  modules/shared/components/molecules/MessageBox/types/EMessageBox.ts
  modules/shared/components/molecules/MessageBox/types/IMessageBox.d.ts
  modules/shared/components/molecules/Misc/Misc.stories.tsx
  modules/shared/components/molecules/Misc/Misc.tsx
  modules/shared/components/molecules/Misc/types/IMisc.d.ts
  modules/shared/components/molecules/UploadingImage/UploadingImage.test.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
Labels: ready-for-merge

#329 Firebase auth
  context/AuthUserContext/AuthUserContext.tsx
  context/AuthUserContext/api/IAuth.d.ts
  context/AuthUserContext/api/authApi.ts
  context/AuthUserContext/hooks/useFirebaseAuth/IUseFirebaseAuth.d.ts
  context/AuthUserContext/hooks/useFirebaseAuth/useFirebaseAuth.ts
  modules/HomePage/api/DeletePostApi/IDeletePostsApi.d.ts
  modules/HomePage/api/DeletePostApi/deletePostHelpers.ts
  modules/HomePage/api/DeletePostApi/deletePosts.test.ts
  modules/HomePage/api/DeletePostApi/deletePostsApi.ts
  modules/HomePage/api/votesApi/IvotesApi.d.ts
  modules/HomePage/api/votesApi/voteApi.test.ts
  modules/HomePage/api/votesApi/voteApi.ts
  modules/HomePage/api/votesApi/votesHelpers.ts
  modules/HomePage/components/NewPost/NewPost.test.tsx
  modules/HomePage/components/NewPost/NewPost.tsx
  modules/HomePage/components/Posts/Posts.tsx
  modules/Login/index.tsx
  modules/Login/pages/Login.tsx
  modules/shared/api/auth.ts
  modules/shared/api/createPollPost.ts
  modules/shared/api/getPosts.api.ts
  modules/shared/api/postsApi.api.ts
  modules/shared/components/molecules/Navigation/Navigation.stories.tsx
  modules/shared/components/molecules/Navigation/Navigation.test.tsx
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  modules/shared/logic/userAuth/ICookieCutter.d.ts
  modules/shared/logic/userAuth/userAuth.ts
  modules/shared/logic/userId/userId.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/login/index.tsx
  yarn.lock
Labels: ready-for-review

#335 Share Post URL
  modules/HomePage/components/Posts/Posts.tsx
  modules/shared/components/molecules/postFooter/IPostFooter.d.ts
  modules/shared/components/molecules/postFooter/PostFooter.test.tsx
  modules/shared/components/molecules/postFooter/PostFooter.tsx
  modules/shared/components/molecules/postFooter/__snapshots__/PostFooter.test.tsx.snap
  modules/shared/components/organisms/ImagePollView/IImagePollView.d.ts
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/MiniSurveyView/IMiniSurveyView.d.ts
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.test.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/ITextPollView.d.ts
  modules/shared/components/organisms/TextPollView/TextPollView.test.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
Labels: ready-for-merge

#334 Add @modules to webpack aliases
  .storybook/main.js
Labels: ready-for-merge
