Repository m3ntorship/pickify-frontend, pull requests merged in 2021-06, with the labels that each got.

#134 fixed a typo
  modules/shared/components/atoms/Avatar/Avatar.module.css
  modules/shared/components/atoms/Avatar/Avatar.stories.tsx
  modules/shared/components/atoms/Avatar/Avatar.test.tsx
  modules/shared/components/atoms/Avatar/Avatar.tsx
  modules/shared/components/atoms/Avatar/IAvatar.d.ts
  modules/shared/components/atoms/Avatar/__snapshots__/Avatar.test.tsx.snap
  modules/shared/components/molecules/UserInfo/IUserInfo.d.ts
  modules/shared/components/molecules/UserInfo/Index.tsx
  modules/shared/logic/avatarLogic/avatarLogic.test.ts
  modules/shared/logic/avatarLogic/avatarLogic.ts
Labels: ready-for-review

#123 Fetching posts
  .eslintrc.js
  modules/shared/api/IGetPosts.d.ts
  modules/shared/api/getPosts.api.ts
  modules/shared/api/postsApi.api.ts
  modules/shared/api/postsMockedData.ts
  modules/shared/components/HOC/WithErrorHandler/IDataTests.d.ts
  modules/shared/components/HOC/WithErrorHandler/IwithErrorHandler.d.ts
  modules/shared/components/HOC/WithErrorHandler/WithErrorHandler.test.tsx
  modules/shared/components/HOC/WithErrorHandler/WithErrorHandler.tsx
  modules/shared/components/molecules/Privacy/index.tsx
  modules/shared/types/postFeed/EPostType.ts
  modules/shared/types/postFeed/IPostFeed.d.ts
  package.json
  pages/index.tsx
  yarn.lock
Labels: changes requested, ready-for-review

#146 Fix storybook issue
  .storybook/main.js
Labels: ready-for-review

#128 Create option group component
  modules/shared/components/molecules/optionGroup/IOptionGroup.d.ts
  modules/shared/components/molecules/optionGroup/OptionGroup.module.css
  modules/shared/components/molecules/optionGroup/OptionGroup.stories.tsx
  modules/shared/components/molecules/optionGroup/OptionGroup.test.tsx
  modules/shared/components/molecules/optionGroup/OptionGroup.tsx
  modules/shared/components/molecules/optionGroup/__snapshots__/OptionGroup.test.tsx.snap
  modules/shared/components/molecules/optionGroup/data.ts
Labels: in-progress

#150 updated types + added text poll filter
  modules/shared/api/getPosts.api.ts
  modules/shared/api/postsMockedData.ts
  modules/shared/types/postFeed/IPostFeed.d.ts
  pages/index.tsx
Labels: ready-for-review

#149 created Widget component
  modules/shared/components/atoms/Widget/Widget.module.css
  modules/shared/components/atoms/Widget/Widget.stories.tsx
  modules/shared/components/atoms/Widget/Widget.test.tsx
  modules/shared/components/atoms/Widget/Widget.tsx
  modules/shared/components/atoms/Widget/__snapshots__/Widget.test.tsx.snap
  tailwind.config.js
Labels: ready-for-review

#152 created home page
  modules/HomePage/components/Posts.tsx
  modules/HomePage/index.tsx
  modules/HomePage/pages/home-page.module.css
  modules/HomePage/pages/home-page.tsx
  modules/shared/components/molecules/Navigation/Navigation.module.css
  pages/index.tsx
  tailwind.config.js
Labels: ready-for-review

#131 Slider component
  modules/shared/components/atoms/Slider/ISlider.d.ts
  modules/shared/components/atoms/Slider/Slider.module.css
  modules/shared/components/atoms/Slider/Slider.stories.tsx
  modules/shared/components/atoms/Slider/Slider.test.tsx
  modules/shared/components/atoms/Slider/Slider.tsx
  modules/shared/components/atoms/Slider/__snapshots__/Slider.test.tsx.snap
Labels: ready-for-review

#158 Enhanced text poll component
  modules/HomePage/components/Posts.tsx
  modules/shared/api/postsMockedData.ts
  modules/shared/components/molecules/TextPollViewOptions/ITextPollViewOptions.d.ts
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.stories.tsx
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.test.tsx
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.tsx
  modules/shared/components/molecules/TextPollViewOptions/__snapshots__/TextPollViewOptions.test.tsx.snap
  modules/shared/components/molecules/TextPollViewOptions/data.ts
  modules/shared/components/molecules/optionGroup/OptionGroup.module.css
  modules/shared/components/molecules/optionGroup/OptionGroup.stories.tsx
  modules/shared/components/molecules/optionGroup/OptionGroup.tsx
  modules/shared/components/molecules/optionGroup/__snapshots__/OptionGroup.test.tsx.snap
  modules/shared/components/organisms/TextPollView/ITextPollView.d.ts
  modules/shared/components/organisms/TextPollView/TextPollView.stories.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/types/postFeed/IPostFeed.d.ts
Labels: ready-for-review

#157 Removed unnecessary example files
  modules/example/api/example-one.api.ts
  modules/example/components/example-one/DumbComponent.tsx
  modules/example/components/example-one/index.stories.js
  modules/example/components/example-one/index.stories.mdx
  modules/example/components/example-one/index.stories.tsx
  modules/example/components/example-one/index.tsx
  modules/example/hooks/example.hook.ts
  modules/example/index.ts
  modules/example/logic/example-one.logic.ts
  modules/example/pages/example-one.page.tsx
  modules/example/tests/example-one.test.ts
  modules/shared/api/example1.api.ts
  modules/shared/components/example1/index.tsx
  modules/shared/hooks/shared-example.hook.ts
  modules/shared/index.ts
  modules/shared/logic/example1.logic.ts
  modules/shared/tests/example1.test.ts
  pages/example.tsx
Labels: ready-for-merge, ready-for-review

#161 added necessary tailwind values
  tailwind.config.js
Labels: ready-for-review

#163 added fill varaiants and colors
  tailwind.config.js
Labels: ready-for-review

#103 Create image upload component #81
  modules/shared/components/atoms/ImageUpload/IImageUpload.d.ts
  modules/shared/components/atoms/ImageUpload/ImageUpload.test.tsx
  modules/shared/components/atoms/ImageUpload/imageUpload.module.css
  modules/shared/components/atoms/ImageUpload/index.stories.tsx
  modules/shared/components/atoms/ImageUpload/index.tsx
  modules/shared/components/icons/image.svg
  modules/shared/components/molecules/Privacy/__snapshots__/privacy.test.tsx.snap
Labels: ready-for-review

#165 Fixed ring color and opacity in VoteIcon component
  modules/shared/components/atoms/VoteIcon/VoteIcon.module.css
  modules/shared/components/atoms/VoteIcon/VoteIcon.tsx
  modules/shared/components/atoms/VoteIcon/__snapshots__/VoteIcon.test.tsx.snap
Labels: ready-for-review

#168 added image poll option to mocked data
  modules/shared/api/postsMockedData.ts
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.stories.tsx
  modules/shared/components/organisms/TextPollView/TextPollView.stories.tsx
  modules/shared/types/postFeed/IPostFeed.d.ts
  pages/index.tsx
Labels: ready-for-review

#129 added imageCaption Component
  modules/shared/components/molecules/imageCaption/IImageCaption.d.ts
  modules/shared/components/molecules/imageCaption/ImageCaption.stories.tsx
  modules/shared/components/molecules/imageCaption/ImageCaption.test.tsx
  modules/shared/components/molecules/imageCaption/ImageCaption.tsx
  modules/shared/components/molecules/imageCaption/__snapshots__/ImageCaption.test.tsx.snap
  modules/shared/components/molecules/imageCaption/imageCaption.module.css
Labels: changes requested, ready-for-review

#169 deleted redundant imageCaption folder
  modules/shared/components/molecules/imageCaption/IImageCaption.d.ts
  modules/shared/components/molecules/imageCaption/ImageCaption.stories.tsx
  modules/shared/components/molecules/imageCaption/ImageCaption.test.tsx
  modules/shared/components/molecules/imageCaption/ImageCaption.tsx
  modules/shared/components/molecules/imageCaption/__snapshots__/ImageCaption.test.tsx.snap
  modules/shared/components/molecules/imageCaption/imageCaption.module.css
Labels: ready-for-review

#175 Tab group
  modules/shared/components/atoms/Tab/ITab.d.ts
  modules/shared/components/atoms/Tab/Tab.module.css
  modules/shared/components/atoms/Tab/Tab.stories.tsx
  modules/shared/components/atoms/Tab/Tab.test.tsx
  modules/shared/components/atoms/Tab/Tab.tsx
  modules/shared/components/atoms/Tab/__snapshots__/Tab.test.tsx.snap
  modules/shared/components/icons/imagePoll.svg
  modules/shared/components/icons/miniSurvey.svg
  modules/shared/components/icons/textPoll.svg
  modules/shared/components/molecules/TabGroup/ITabGroup.d.ts
  modules/shared/components/molecules/TabGroup/TabGroup.stories.tsx
  modules/shared/components/molecules/TabGroup/TabGroup.test.tsx
  modules/shared/components/molecules/TabGroup/TabGroup.tsx
  modules/shared/components/molecules/TabGroup/data.tsx
Labels: ready-for-review

#182 added types and tests to TextInput
  modules/shared/components/atoms/TextInputs/TextInput.stories.tsx
  modules/shared/components/atoms/TextInputs/TextInput.test.tsx
  modules/shared/components/atoms/TextInputs/TextInput.tsx
  modules/shared/components/atoms/TextInputs/__snapshots__/TextInput.test.tsx.snap
  modules/shared/components/atoms/TextInputs/types/ITextInputs.d.ts
Labels: ready-for-review

#177 created CreatePostHeader component
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.stories.tsx
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.test.tsx
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.tsx
  modules/shared/components/molecules/CreatePostHeader/ICreatePostHeader.d.ts
  modules/shared/components/molecules/CreatePostHeader/__snapshots__/CreatePostHeader.test.tsx.snap
Labels: changes requested, ready-for-review

#179 done some adjustment to improve the button atom
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/Button.stories.tsx
  modules/shared/components/atoms/Button/Button.test.tsx
  modules/shared/components/atoms/Button/Button.tsx
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/atoms/Button/types/IButton.d.ts
  tailwind.config.js
Labels: changes requested, ready-for-review

#183 adjusted the enum file in the button atom
  modules/shared/components/atoms/Button/types/EButton.ts
Labels: ready-for-review

#184 Create button component
  modules/shared/components/atoms/Button/Button.tsx
  modules/shared/components/atoms/Button/types/IButton.d.ts
Labels: ready-for-review

#171 Create post footer creation component
  modules/shared/components/molecules/PostFooterCreation/IPostFooterCreation.d.ts
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.module.css
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.stories.tsx
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.test.tsx
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.tsx
  modules/shared/components/molecules/PostFooterCreation/__snapshots__/PostFooterCreation.test.tsx.snap
  modules/shared/components/molecules/Privacy/Privacy.module.css
  modules/shared/components/molecules/Privacy/Privacy.stories.tsx
  modules/shared/components/molecules/Privacy/Privacy.tsx
  modules/shared/components/molecules/Privacy/privacy.test.tsx
Labels: ready-for-review

#185 Feature/textdefault
  modules/HomePage/components/Posts.tsx
  modules/shared/components/atoms/TextInputs/TextInput.tsx
  modules/shared/components/atoms/TextInputs/types/ITextInputs.d.ts
  modules/shared/components/icons/checkMarkSmall.svg
  modules/shared/components/icons/delete.svg
  modules/shared/components/icons/drag.svg
  modules/shared/components/icons/plus.svg
  modules/shared/components/icons/plusCircle.svg
  modules/shared/components/icons/verticalThreeDots.svg
  modules/shared/components/icons/xicon.svg
  modules/shared/components/molecules/MiniSurveyCreationBody/IMiniSurveyCreationBody.d.ts
  modules/shared/components/molecules/MiniSurveyCreationBody/MiniSurveyCreationBody.stories.tsx
  modules/shared/components/molecules/MiniSurveyCreationBody/MiniSurveyCreationBody.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.stories.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.tsx
  modules/shared/components/molecules/OptionGroup/types/IOptionGroup.d.ts
  modules/shared/components/molecules/OptionGroups/OptionGroups.stories.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroupsHeader/IOptionGroupHeader.d.ts
  modules/shared/components/molecules/OptionGroups/OptionGroupsHeader/OptionGroupHeader.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/TextDefault/TextDefault.stories.tsx
  modules/shared/components/molecules/TextDefault/TextDefault.tsx
  modules/shared/components/molecules/TextDefault/types/TextDefault.d.ts
  modules/shared/components/organisms/TextPollCreation/TextPollCreation.stories.tsx
  modules/shared/components/organisms/TextPollCreation/TextPollCreation.tsx
  modules/shared/components/organisms/TextPollCreation/types/ITextPollCreation.d.ts
  package.json
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ready-for-review

#174 Create uploading image component
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/Button.stories.tsx
  modules/shared/components/atoms/Button/Button.test.tsx
  modules/shared/components/atoms/Button/Button.tsx
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/atoms/Button/types/IButton.d.ts
  modules/shared/components/molecules/Misc/Misc.module.css
  modules/shared/components/molecules/UploadingImage/IUploadingImage.d.ts
  modules/shared/components/molecules/UploadingImage/UploadingImage.module.css
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/CreateImagePoll/CreateImagePoll.stories.tsx
  modules/shared/components/organisms/CreateImagePoll/CreateImagePoll.tsx
  modules/shared/components/organisms/CreateImagePoll/ICreateImagePoll.d.ts
  modules/shared/components/organisms/CreateImagePoll/validateUploadedImages.ts
  modules/shared/logic/createImagePoll/createImagePoll.ts
  tailwind.config.js
Labels: ready-for-review

#188 Create post footer creation component
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.tsx
  modules/shared/components/molecules/PostFooterCreation/__snapshots__/PostFooterCreation.test.tsx.snap
Labels: ready-for-review

#191 Fix responsive look and feel
  modules/HomePage/pages/home-page.module.css
  modules/shared/components/icons/menu.svg
  modules/shared/components/molecules/Navigation/Navigation.module.css
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
Labels: ready-for-review

#193 CreateImagePoll state adjusments
  modules/HomePage/pages/home-page.module.css
  modules/shared/components/molecules/Navigation/Navigation.module.css
  modules/shared/components/molecules/UploadingImage/IUploadingImage.d.ts
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/CreateImagePoll/CreateImagePoll.tsx
  modules/shared/components/organisms/CreateImagePoll/ICreateImagePoll.d.ts
  modules/shared/components/organisms/CreateImagePoll/validateUploadedImages.ts
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
Labels: ready-for-review

#212 Refactor upload button componen
  modules/shared/components/atoms/FileUploader/FileUploader.module.css
  modules/shared/components/atoms/FileUploader/FileUploader.stories.tsx
  modules/shared/components/atoms/FileUploader/FileUploader.test.tsx
  modules/shared/components/atoms/FileUploader/FileUploader.tsx
  modules/shared/components/atoms/FileUploader/IFileUploader.d.ts
  modules/shared/components/atoms/ImageUpload/IImageUpload.d.ts
  modules/shared/components/atoms/ImageUpload/ImageUpload.test.tsx
  modules/shared/components/atoms/ImageUpload/imageUpload.module.css
  modules/shared/components/atoms/ImageUpload/index.stories.tsx
  modules/shared/components/atoms/ImageUpload/index.tsx
  modules/shared/components/icons/image.svg
  modules/shared/components/molecules/MiniSurveyCreationBody/MiniSurveyCreationBody.tsx
  modules/shared/components/molecules/Misc/Misc.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.test.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/CreateImagePoll/CreateImagePoll.tsx
  modules/shared/components/organisms/CreateImagePoll/ICreateImagePoll.d.ts
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/logic/uploadedFiles/IUploadedFiles.d.ts
  modules/shared/logic/uploadedFiles/uploadedFiles.test.ts
  modules/shared/logic/uploadedFiles/uploadedFiles.ts
Labels: ready-for-review

#170 Image poll group view
  .stylelintrc.js
  modules/HomePage/components/Posts.tsx
  modules/shared/components/molecules/ImageCaption/ImageCaption.module.css
  modules/shared/components/molecules/ImageCaption/ImageCaption.tsx
  modules/shared/components/molecules/ImageCaption/__snapshots__/ImageCaption.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/IImagePollGroup.d.ts
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.module.css
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.stories.tsx
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.test.tsx
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/data.ts
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/organisms/ImagePollView/IImagePollView.d.ts
  modules/shared/components/organisms/ImagePollView/ImagePollView.stories.tsx
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/index.ts
  tailwind.config.js
Labels: ready-for-review

#210 Add MiniSurveyView tests
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.test.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
Labels: ready-for-merge

#205 Add TextDefault tests
  modules/shared/components/molecules/TextDefault/TextDefault.test.tsx
  modules/shared/components/molecules/TextDefault/TextDefault.tsx
Labels: ready-for-merge

#207 refactor OptionGroup and optionGroups components and add tests
  modules/shared/components/molecules/Option/Option.stories.tsx
  modules/shared/components/molecules/Option/Option.test.tsx
  modules/shared/components/molecules/Option/Option.tsx
  modules/shared/components/molecules/Option/types/Option.d.ts
  modules/shared/components/molecules/OptionGroup/OptionGroup.test.tsx
  modules/shared/components/molecules/OptionGroup/OptionGroup.tsx
  modules/shared/components/molecules/OptionGroupWrapper/IOptionGroupWrapper.d.ts
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupWrapper.stories.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupWrapper.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/IOptionGroupHeader.d.ts
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.test.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.stories.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.tsx
  modules/shared/components/molecules/TextDefault/TextDefault.stories.tsx
  pages/articles/index.tsx
Labels: ready-for-review

#225 Add MiniSurveyPollCreation tests
  modules/shared/components/molecules/OptionGroups/OptionGroups.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.test.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
Labels: ready-for-review

#227 added tests for TextPollCreation organism
  modules/shared/components/organisms/TextPollCreation/TextPollCreation.test.tsx
Labels: ready-for-review

#249 Login icon mobile view
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
  modules/shared/logic/userId/userId.ts
Labels: ready-for-review
