Repository m3ntorship/pickify-frontend, pull requests merged in 2021-08, with the labels that each got.

#340 Display post in separate page
  modules/HomePage/components/Posts/Posts.tsx
  modules/HomePage/components/Posts/PostsHelpers.ts
  modules/Post/IPost.d.ts
  modules/Post/Post.module.css
  modules/Post/Post.tsx
  modules/shared/api/IGetSinglePost.d.ts
  modules/shared/api/getSinglePost.ts
  modules/shared/api/postsApi.api.ts
  modules/shared/components/organisms/SinglePostView/ISinglePostView.d.ts
  modules/shared/components/organisms/SinglePostView/SinglePostView.module.css
  modules/shared/components/organisms/SinglePostView/SinglePostView.tsx
  modules/shared/types/seperatePost/ISeparatePost.d.ts
  pages/index.tsx
  pages/posts/[id].tsx
Labels: in-progress, ready-for-review

#344 added the default path for the setCookie function
  modules/shared/logic/userAuth/userAuth.ts
Labels: in-progress

#341 Logout with dropdown menu
  modules/shared/components/atoms/DropDown/DropDown.module.css
  modules/shared/components/atoms/DropDown/DropDown.tsx
  modules/shared/components/atoms/DropDown/__snapshots__/DropDown.test.tsx.snap
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
Labels: ready-for-review

#346 validate the url uuid
  pages/posts/[id].tsx
Labels: ready-for-review

#350 Redirect to post page
  modules/Login/pages/Login.tsx
  modules/Post/Post.tsx
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  modules/shared/logic/userAuth/userAuth.ts
  package.json
  pages/posts/[id].tsx
  yarn.lock
Labels: ready-for-merge

#353 Made env variables accessible for production
  .env.example
  .env.production
Labels: ready-for-review

#356 resolved API key test errors
  .env.test
  context/AuthUserContext/api/authApi.ts
  jest.config.js
  modules/HomePage/components/NewPost/NewPost.test.tsx
  modules/shared/components/molecules/Navigation/Navigation.test.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  package.json
  setupEnv.ts
  yarn.lock
Labels: ready-for-review

#360 Change post component name
  modules/PostPage/IPostPage.d.ts
  modules/PostPage/Post.module.css
  modules/PostPage/PostPage.tsx
  modules/shared/types/post/IPost.d.ts
  pages/posts/[id].tsx
Labels: ready-for-review

#371 Picikify logo functionality
  .eslintrc.js
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
Labels: ready-for-review

#376 persist the post footer layout
  modules/shared/components/molecules/postFooter/PostFooter.tsx
Labels: ready-for-review

#374 Feature/infinite scroll
  modules/HomePage/components/Posts/Posts.tsx
  modules/shared/api/getPosts.api.ts
  modules/shared/configuration/ConfigPostCreation/config.ts
  modules/shared/types/postFeed/IPostFeed.d.ts
  package.json
  pages/index.tsx
  yarn.lock
Labels: ready-for-review

#377 Mini survey result view
  modules/shared/components/atoms/TextOptionViewUncoverd/ITextOptionViewUncoverd.d.ts
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncovered.test.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/__snapshots__/TextOptionViewUncovered.test.tsx.snap
  modules/shared/components/molecules/MiniSurveyViewOptions/IMiniSurveyViewOptions.d.ts
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.test.tsx
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.tsx
  modules/shared/components/molecules/MiniSurveyViewOptions/__snapshots__/MiniSurveyViewOptions.test.tsx.snap
  modules/shared/components/molecules/OptionGroupView/IOptionGroupView.d.ts
  modules/shared/components/molecules/OptionGroupView/OptionGroupView.tsx
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
Labels: under review, ready-for-review

#379 Made redirect function more generic
  modules/Login/pages/Login.tsx
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  pages/posts/[id].tsx
Labels: ready-for-review

#387 added the scroll up solution
  package.json
  pages/_app.tsx
  yarn.lock
Labels: ready-for-review

#396 Feature/footer component
  modules/shared/components/molecules/Footer/Footer.module.css
  modules/shared/components/molecules/Footer/Footer.stories.tsx
  modules/shared/components/molecules/Footer/Footer.tsx
  modules/shared/components/molecules/Footer/footerData.ts
  modules/shared/components/molecules/Footer/footerLogic/footerLogic.test.ts
  modules/shared/components/molecules/Footer/footerLogic/footerLogic.ts
Labels: under review, ready-for-review

#390 Improve navigation
  modules/shared/components/icons/home.svg
  modules/shared/components/icons/logo.svg
  modules/shared/components/molecules/Navigation/Navigation.module.css
  modules/shared/components/molecules/Navigation/Navigation.test.tsx
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/__snapshots__/Navigation.test.tsx.snap
  pages/_app.module.css
  pages/_app.tsx
  tailwind.config.js
Labels: ready-for-review

#386 update Readme file structure
  README.md
Labels: under review, ready-for-review

#392 Widgets
  modules/HomePage/pages/home-page.tsx
  modules/Login/pages/Login.module.css
  modules/shared/components/icons/addFriend.svg
  modules/shared/components/icons/deleteFriend.svg
  modules/shared/components/molecules/DeveloperPics/DeveloperPics.stories.tsx
  modules/shared/components/molecules/DeveloperPics/DeveloperPics.test.tsx
  modules/shared/components/molecules/DeveloperPics/DeveloperPics.tsx
  modules/shared/components/molecules/DeveloperPics/images.ts
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.module.css
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.stories.tsx
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.test.tsx
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  modules/shared/components/molecules/FriendSuggestion/IFriendSuggestion.d.ts
  modules/shared/components/molecules/FriendSuggestion/__snapshots__/FriendSuggestion.test.tsx.snap
  modules/shared/components/molecules/TrendeingQuestion/ITrendingQuestion.d.ts
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.module.css
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.stories.tsx
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.test.tsx
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.tsx
  modules/shared/components/organisms/FriendSuggestions/FriendSuggestions.stories.tsx
  modules/shared/components/organisms/FriendSuggestions/FriendSuggestions.test.tsx
  modules/shared/components/organisms/FriendSuggestions/FriendSuggestions.tsx
  modules/shared/components/organisms/FriendSuggestions/dummyData.ts
  modules/shared/components/organisms/TrendingQuestions/TrendingQuestions.stories.tsx
  modules/shared/components/organisms/TrendingQuestions/TrendingQuestions.test.tsx
  modules/shared/components/organisms/TrendingQuestions/TrendingQuestions.tsx
  modules/shared/components/organisms/TrendingQuestions/dummyData.ts
  modules/shared/components/organisms/Widgets/Widgets.module.css
  modules/shared/components/organisms/Widgets/Widgets.stories.tsx
  modules/shared/components/organisms/Widgets/Widgets.tsx
  modules/shared/types/postFeed/IPostFeed.d.ts
  pages/_app.module.css
  pages/_app.tsx
  public/Adel.jpg
  public/Ali.jpeg
  public/Amr.jpeg
  public/Ayoub.jpeg
  public/Elhaw.jpeg
  public/Essam.jpeg
  public/Omar.jpg
  public/Sahl.jpeg
  public/Samy.jpeg
  public/Sayad.jpg
  public/Seif.jpeg
  public/Shaf3y.jpeg
  public/Twfiek.jpeg
  tailwind.config.js
Labels: changes requested

#409 Profile Page
  modules/ProfilePage/index.ts
  modules/ProfilePage/pages/profile-page.module.css
  modules/ProfilePage/pages/profile-page.tsx
  modules/shared/components/atoms/ProfileImagePostLoader/ProfileImagePostLoader.stories.tsx
  modules/shared/components/atoms/ProfileImagePostLoader/ProfileImagePostLoader.tsx
  modules/shared/components/atoms/ProfileTextPostLoader/ProfileTextPostLoader.stories.tsx
  modules/shared/components/atoms/ProfileTextPostLoader/ProfileTextPostLoader.tsx
  modules/shared/components/atoms/ProfileUserLoader/ProfileUserLoader.stories.tsx
  modules/shared/components/atoms/ProfileUserLoader/ProfileUserLoader.tsx
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/organisms/Widgets/Widgets.tsx
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  package.json
  pages/profile/index.tsx
  yarn.lock
Labels: in-progress

#414 Scroll top button
  pages/_app.tsx
Labels: ready-for-review

#407 Notification Page
  modules/NotificationPage/NotificationPage.tsx
  modules/NotificationsPage/NotificationsPage.tsx
  modules/shared/components/atoms/NotificationLoader/NotificationLoader.stories.tsx
  modules/shared/components/atoms/NotificationLoader/NotificationLoader.tsx
  modules/shared/components/molecules/Navigation/Navigation.tsx
  pages/notification/index.tsx
  pages/notifications/index.tsx
Labels: in-progress

#416 Scroll top button
  pages/_app.tsx
Labels: ready-for-review

#417 Navbar modifications
  modules/HomePage/components/Posts/Posts.tsx
  modules/shared/components/icons/bill.svg
  modules/shared/components/icons/friends.svg
  modules/shared/components/icons/help.svg
  modules/shared/components/icons/home.svg
  modules/shared/components/molecules/Navigation/INavigation.d.ts
  modules/shared/components/molecules/Navigation/Navigation.module.css
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/navLinksData.tsx
  tailwind.config.js
Labels: ready-for-review

#423 Reusable Box component
  modules/shared/components/atoms/Box/Box.module.css
  modules/shared/components/atoms/Box/Box.stories.tsx
  modules/shared/components/atoms/Box/Box.test.tsx
  modules/shared/components/atoms/Box/Box.tsx
  modules/shared/components/atoms/Box/IBox.d.ts
  modules/shared/components/atoms/Box/__snapshots__/Box.test.tsx.snap
  modules/shared/components/atoms/Widget/Widget.module.css
  modules/shared/components/atoms/Widget/Widget.stories.tsx
  modules/shared/components/atoms/Widget/Widget.test.tsx
  modules/shared/components/atoms/Widget/Widget.tsx
  modules/shared/components/atoms/Widget/__snapshots__/Widget.test.tsx.snap
  modules/shared/components/molecules/DeveloperPics/DeveloperPics.tsx
  modules/shared/components/organisms/FriendSuggestions/FriendSuggestions.tsx
  modules/shared/components/organisms/TrendingQuestions/TrendingQuestions.tsx
  modules/shared/components/organisms/Widgets/Widgets.tsx
Labels: under review, ready-for-review

#421 refactor user info component
  modules/shared/components/atoms/Avatar/Avatar.stories.tsx
  modules/shared/components/atoms/Avatar/Avatar.tsx
  modules/shared/components/atoms/Avatar/__snapshots__/Avatar.test.tsx.snap
  modules/shared/components/molecules/CreatePostHeader/__snapshots__/CreatePostHeader.test.tsx.snap
  modules/shared/components/molecules/PostViewHeader/IPostViewHeader.d.ts
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.stories.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/UserInfo/IUserInfo.d.ts
  modules/shared/components/molecules/UserInfo/UserInfo.module.css
  modules/shared/components/molecules/UserInfo/UserInfo.stories.tsx
  modules/shared/components/molecules/UserInfo/UserInfo.test.tsx
  modules/shared/components/molecules/UserInfo/UserInfo.tsx
  modules/shared/components/molecules/UserInfo/__snapshots__/UserInfo.test.tsx.snap
  modules/shared/components/organisms/ImagePollView/ImagePollView.tsx
  modules/shared/components/organisms/MiniSurveyView/MiniSurveyView.tsx
  modules/shared/components/organisms/MiniSurveyView/__snapshots__/MiniSurveyView.test.tsx.snap
  modules/shared/components/organisms/TextPollView/TextPollView.tsx
  modules/shared/components/organisms/TextPollView/__snapshots__/TextPollView.test.tsx.snap
  modules/shared/logic/formatDate/FormatDate.ts
  modules/shared/logic/userInfoVariant/userInfoVariant.test.ts
  modules/shared/logic/userInfoVariant/userInfoVariant.ts
Labels: ready-for-review

#420 Search bar
  modules/Login/pages/Login.tsx
  modules/Login/pages/__snapshots__/Login.test.tsx.snap
  modules/shared/components/atoms/TextInputs/TextInput.tsx
  modules/shared/components/atoms/TextInputs/types/ETextInput.ts
  modules/shared/components/icons/search.svg
  modules/shared/components/molecules/Navigation/Navigation.module.css
  modules/shared/components/molecules/Navigation/Navigation.tsx
Labels: ready-for-review

#410 Feedback Feature
  modules/shared/components/icons/amazing.svg
  modules/shared/components/icons/bad.svg
  modules/shared/components/icons/good.svg
  modules/shared/components/icons/neutral.svg
  modules/shared/components/icons/terrible.svg
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/Feedback/Feedback.stories.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
  tailwind.config.js
Labels: in-progress

#438 Refactor post creation with box component
  modules/HomePage/components/NewPost/NewPost.module.css
  modules/HomePage/components/NewPost/NewPost.tsx
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.tsx
  modules/shared/components/molecules/CreatePostHeader/__snapshots__/CreatePostHeader.test.tsx.snap
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.module.css
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.tsx
  modules/shared/components/molecules/PostFooterCreation/__snapshots__/PostFooterCreation.test.tsx.snap
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/ImagePollCreation/ImagePollCreation.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  modules/shared/components/organisms/TextPollCreation/TextPollCreation.tsx
Labels: ready-for-review

#433 Refactor pages
  modules/FriendsPage/FriendsPage.module.css
  modules/FriendsPage/FriendsPage.tsx
  modules/HomePage/pages/FriendsPage/FriendsPage.module.css
  modules/HomePage/pages/FriendsPage/FriendsPage.tsx
  modules/Login/pages/Login.module.css
  modules/Login/pages/Login.tsx
  modules/Login/pages/__snapshots__/Login.test.tsx.snap
  modules/NotificationPage/NotificationPage.tsx
  modules/NotificationsPage/NotificationsPage.tsx
  modules/ProfilePage/index.ts
  modules/ProfilePage/pages/ProfilePage.module.css
  modules/ProfilePage/pages/ProfilePage.tsx
  modules/ProfilePage/pages/profile-page.module.css
  modules/ProfilePage/pages/profile-page.tsx
  modules/shared/components/atoms/LoaderMessage/LoaderMessage.module.css
  modules/shared/components/atoms/LoaderMessage/LoaderMessage.test.tsx
  modules/shared/components/atoms/LoaderMessage/LoaderMessage.tsx
  modules/shared/components/atoms/LoaderMessage/__snapshots__/LoaderMessage.test.tsx.snap
  modules/shared/components/atoms/PageHeader/PageHeader.test.tsx
  modules/shared/components/atoms/PageHeader/PageHeader.tsx
  modules/shared/components/atoms/PageHeader/__snapshots__/PageHeader.test.tsx.snap
  modules/shared/logic/capitalizeFirstLetterOfEveryWord/capitalizeFirstLetterOfEveryWord.test.ts
  modules/shared/logic/capitalizeFirstLetterOfEveryWord/capitalizeFirstLetterOfEveryWord.ts
  pages/friends/index.tsx
  pages/notification/index.tsx
Labels: ready-for-review

#435 improve the feedback feature
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/Feedback/Feedback.test.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
  modules/shared/components/organisms/Feedback/__snapshots__/Feedback.test.tsx.snap
Labels: ready-for-review

#443 Solved post page responsiveness
  modules/PostPage/PostPage.tsx
Labels: ready-for-review

#395 Improve Button component
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/Button.stories.tsx
  modules/shared/components/atoms/Button/Button.test.tsx
  modules/shared/components/atoms/Button/Button.tsx
  modules/shared/components/atoms/Button/__snapshots__/Button.test.tsx.snap
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/atoms/Button/types/IButton.d.ts
  modules/shared/components/atoms/ImagePollCovered/ImagePollCovered.module.css
  modules/shared/components/atoms/ImagePollCovered/ImagePollCovered.tsx
  modules/shared/components/atoms/ImagePollCovered/__snapshots__/ImagePollCovered.test.tsx.snap
  modules/shared/components/icons/addFriend.svg
  modules/shared/components/icons/arrowDown.svg
  modules/shared/components/icons/buttonArowDown.svg
  modules/shared/components/icons/deleteFriend.svg
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.module.css
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  modules/shared/components/molecules/FriendSuggestion/__snapshots__/FriendSuggestion.test.tsx.snap
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/PostFooterCreation/__snapshots__/PostFooterCreation.test.tsx.snap
  modules/shared/components/molecules/SignleImagePollOption/__snapshots__/SignleImagePollOption.test.tsx.snap
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.module.css
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.tsx
  pages/_app.tsx
Labels: in-progress

#448 Added icon for expand results button
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.tsx
  tailwind.config.js
Labels: ready-for-review

#446 handled the time when to stop getting more posts
  modules/HomePage/components/Posts/Posts.tsx
Labels: ready-for-review

#450 Fixed a typo and solved some issues in ImagePollCovered
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/ImagePollCovered/ImagePollCovered.tsx
  modules/shared/components/atoms/ImagePollCovered/__snapshots__/ImagePollCovered.test.tsx.snap
  modules/shared/components/icons/filledDislike.svg
  modules/shared/components/icons/filledLike.svg
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
  modules/shared/components/molecules/ImagePollGroup/__snapshots__/ImagePollGroup.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/SingleImagePollOption/ISingleImagePollOption.d.ts
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.stories.tsx
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.test.tsx
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.tsx
  modules/shared/components/molecules/SingleImagePollOption/__snapshots__/SingleImagePollOption.test.tsx.snap
  modules/shared/components/molecules/SingleImagePollOption/mockedOptions.ts
Labels: ready-for-review

#451 Add favicon and pages' titles
  modules/FriendsPage/FriendsPage.tsx
  modules/HomePage/pages/home-page.tsx
  modules/Login/pages/Login.tsx
  modules/NotificationsPage/NotificationsPage.tsx
  modules/ProfilePage/pages/ProfilePage.tsx
  pages/_app.tsx
  public/favicon.ico
Labels: ready-for-review

#453 Handle closing feedback popup
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/Navigation/navLinksData.tsx
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/Feedback/Feedback.test.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
  modules/shared/components/organisms/Feedback/__snapshots__/Feedback.test.tsx.snap
Labels: ready-for-review

#455 Fixed spacing issue and used the same layout for single post page
  modules/PostPage/Post.module.css
  modules/PostPage/PostPage.tsx
  pages/_app.tsx
Labels: ready-for-review

#454 Set user id on auth state changed
  context/AuthUserContext/api/authApi.ts
  context/AuthUserContext/hooks/useFirebaseAuth/useFirebaseAuth.ts
  modules/Login/pages/Login.tsx
Labels: ready-for-review

#461 Added protection for notifications, friends and profile pages
  pages/friends/index.tsx
  pages/notifications/index.tsx
  pages/profile/index.tsx
Labels: ready-for-review

#457 scroll-to-top-button fixed
  modules/shared/components/icons/ScrollToTopButton.svg
  pages/_app.tsx
Labels: ready-for-merge

#462 Feedback small screens
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/Button.tsx
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/postFooter/PostFooter.module.css
  modules/shared/components/organisms/Feedback/Feedback.test.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
  modules/shared/components/organisms/Feedback/__snapshots__/Feedback.test.tsx.snap
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
Labels: ready-for-review

#456 adjusted the arrange of the like/dislike button and updated the tests
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.tsx
  modules/shared/components/molecules/SingleImagePollOption/__snapshots__/SingleImagePollOption.test.tsx.snap
Labels: ready-for-merge

#463 improve-single-image-poll-view
  modules/shared/components/molecules/ImagePollUncovered/ImagePollUncovered.tsx
  modules/shared/components/molecules/ImagePollUncovered/types/IImagePollUncovered.d.ts
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.tsx
Labels: ready-for-review

#466 improve the image poll view component
  modules/shared/components/molecules/ImagePollGroup/ImagePollGroup.tsx
  modules/shared/components/molecules/ImagePollOption/IImagePollOption.d.ts
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/ImagePollUncovered/ImagePollUncovered.tsx
  modules/shared/components/molecules/ImagePollUncovered/__snapshots__/ImagePollUncovered.test.tsx.snap
Labels: ready-for-review

#468 updated the imagepolloption tests
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.test.tsx
Labels: in-progress, ready-for-merge

#467 Solved flash of content on login page
  modules/Login/pages/Login.tsx
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/icons/xicon.svg
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  pages/login/index.tsx
Labels: ready-for-review

#471 Solved FriendSuggestion button
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  modules/shared/components/molecules/FriendSuggestion/__snapshots__/FriendSuggestion.test.tsx.snap
Labels: ready-for-review

#478 modified accept property in input type file
  modules/shared/components/atoms/FileUploader/FileUploader.tsx
Labels: ready-for-review

#479 Post creation full screen for mobile
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/molecules/PostFooterCreation/PostFooterCreation.tsx
  modules/shared/components/molecules/PostFooterCreation/__snapshots__/PostFooterCreation.test.tsx.snap
  modules/shared/components/organisms/Modal/Modal.module.css
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
Labels: ready-for-review

#477 Edited collapse/expand button
  modules/shared/components/molecules/MiniSurveyViewOptions/MiniSurveyViewOptions.tsx
Labels: ready-for-review

#482 Solve imported svg using alias issue
  .babelrc
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  package.json
  yarn.lock
Labels: ready-for-review

#484 Used developer pics in friend suggestions
  modules/shared/components/organisms/FriendSuggestions/dummyData.ts
Labels: ready-for-review

#486 fix inputs default innershadow in safari
  modules/shared/components/atoms/TextInputs/TextInput.module.css
Labels: ready-for-review

#485 Use option relative width
  .stylelintrc.js
  modules/shared/components/atoms/Slider/Slider.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.module.css
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/__snapshots__/TextOptionViewUncovered.test.tsx.snap
  modules/shared/components/molecules/ImagePollOption/ImagePollOption.tsx
  modules/shared/components/molecules/ImagePollOption/__snapshots__/ImagePollOption.test.tsx.snap
  modules/shared/components/molecules/TextPollViewOptions/__snapshots__/TextPollViewOptions.test.tsx.snap
Labels: ready-for-review

#494 Use persistent cookies
  modules/shared/logic/userAuth/userAuth.ts
Labels: ready-for-review

#501 refactor the size of the avatar component
  modules/shared/components/atoms/Avatar/Avatar.module.css
  modules/shared/components/atoms/Avatar/Avatar.stories.tsx
  modules/shared/components/atoms/Avatar/Avatar.test.tsx
  modules/shared/components/atoms/Avatar/Avatar.tsx
  modules/shared/components/atoms/Avatar/IAvatar.d.ts
  modules/shared/components/atoms/Avatar/__snapshots__/Avatar.test.tsx.snap
  modules/shared/logic/avatarLogic/avatarLogic.ts
  tailwind.config.js
Labels: ready-for-review
