Repository m3ntorship/pickify-frontend, pull requests merged in 2021-09, with the labels that each got.

#506 Fixed drop down menu
  modules/shared/components/atoms/DropDown/DropDown.module.css
Labels: ready-for-review

#499 adjusted the feedback feature as the new design
  modules/shared/components/icons/feedbackCheckMark.svg
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/Feedback/Feedback.test.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
Labels: ready-for-review

#503 Remove option padding
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.module.css
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncoverd.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/TextOptionViewUncovered.test.tsx
  modules/shared/components/atoms/TextOptionViewUncoverd/__snapshots__/TextOptionViewUncovered.test.tsx.snap
  modules/shared/components/molecules/TextPollViewOptions/__snapshots__/TextPollViewOptions.test.tsx.snap
Labels: ready-for-review

#470 eslint-warning
  context/AuthUserContext/api/authApi.ts
  context/AuthUserContext/hooks/useFirebaseAuth/useFirebaseAuth.ts
  modules/HomePage/api/DeletePostApi/deletePostsApi.ts
  modules/HomePage/api/votesApi/voteApi.ts
  modules/HomePage/components/Posts/Posts.tsx
  modules/Login/pages/Login.tsx
  modules/shared/api/createPollPost.ts
  modules/shared/components/HOC/WithErrorHandler/WithErrorHandler.test.tsx
  modules/shared/components/HOC/WithErrorHandler/WithErrorHandler.tsx
  modules/shared/components/atoms/Divider/Divider.tsx
  modules/shared/components/molecules/Footer/Footer.tsx
  modules/shared/components/molecules/OptionGroupView/OptionGroupView.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/TextPollViewOptions/TextPollViewOptions.tsx
  modules/shared/components/molecules/UploadingImage/UploadingImage.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  modules/shared/components/organisms/SinglePostView/SinglePostView.tsx
  modules/shared/hooks/useUploadedFiles/useUploadedFiles.ts
Labels: ready-for-review, in-progress

#509 Solving eslint warnings
  modules/shared/components/molecules/Footer/Footer.tsx
Labels: ready-for-review

#502 refactor imgwithinfo with compound component
  modules/shared/components/icons/edit.svg
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  modules/shared/components/molecules/FriendSuggestion/__snapshots__/FriendSuggestion.test.tsx.snap
  modules/shared/components/molecules/ImgWithInfo/IImgWithInfo.d.ts
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.stories.tsx
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.test.tsx
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.tsx
  modules/shared/components/molecules/ImgWithInfo/__snapshots__/ImgWithInfo.test.tsx.snap
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.tsx
Labels: ready-for-review

#492 Improve Storybook
  .storybook/main.js
  .storybook/preview.js
  modules/shared/components/molecules/Navigation/Navigation.stories.tsx
  package.json
  yarn.lock
Labels: ready-for-review, in-progress

#508 Reusabe tabs component
  modules/shared/components/atoms/Tab/ITab.d.ts
  modules/shared/components/atoms/Tab/Tab.module.css
  modules/shared/components/atoms/Tab/Tab.stories.tsx
  modules/shared/components/atoms/Tab/Tab.test.tsx
  modules/shared/components/atoms/Tab/Tab.tsx
  modules/shared/components/atoms/Tab/__snapshots__/Tab.test.tsx.snap
  modules/shared/components/molecules/CreatePostHeader/__snapshots__/CreatePostHeader.test.tsx.snap
  modules/shared/components/molecules/TabGroup/ITabGroup.d.ts
  modules/shared/components/molecules/TabGroup/TabGroup.stories.tsx
  modules/shared/components/molecules/TabGroup/TabGroup.tsx
Labels: ready-for-review

#507 Add mini survey group question
  modules/shared/components/atoms/DropDown/DropDown.module.css
  modules/shared/components/atoms/DropDown/DropDown.tsx
  modules/shared/components/atoms/DropDown/__snapshots__/DropDown.test.tsx.snap
  modules/shared/components/atoms/DropDown/mockedOptions.ts
  modules/shared/components/molecules/OptionGroupWrapper/IOptionGroupWrapper.d.ts
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupWrapper.stories.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupWrapper.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/IOptionGroupHeader.d.ts
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.test.tsx
  modules/shared/components/molecules/OptionGroupWrapper/OptionGroupsHeader/OptionGroupHeader.tsx
  modules/shared/components/molecules/OptionGroups/IOptionGroups.d.ts
  modules/shared/components/molecules/OptionGroups/OptionGroups.stories.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.test.tsx
  modules/shared/components/molecules/OptionGroups/OptionGroups.tsx
  modules/shared/components/organisms/Feedback/Feedback.module.css
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.test.tsx
  modules/shared/components/organisms/MiniSurveyPollCreation/MiniSurveyPollCreation.tsx
  modules/shared/types/IPostCreationValidationFields.d.ts
Labels: ready-for-review

#514 ImgWithInfo compound comp enhance
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.stories.tsx
  modules/shared/components/molecules/FriendSuggestion/FriendSuggestion.tsx
  modules/shared/components/molecules/FriendSuggestion/__snapshots__/FriendSuggestion.test.tsx.snap
  modules/shared/components/molecules/ImgWithInfo/IImgWithInfo.d.ts
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.module.css
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.stories.tsx
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.test.tsx
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.tsx
  modules/shared/components/molecules/ImgWithInfo/__snapshots__/ImgWithInfo.test.tsx.snap
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.module.css
  modules/shared/components/molecules/TrendeingQuestion/TrendingQuestion.tsx
Labels: ready-for-review

#515 Credit page
  modules/CreditsPage/components/Credit/Credit.stories.tsx
  modules/CreditsPage/components/Credit/Credit.tsx
  modules/CreditsPage/components/Credit/ICredit.d.ts
  modules/CreditsPage/components/Credits/Credits.stories.tsx
  modules/CreditsPage/components/Credits/Credits.tsx
  modules/CreditsPage/components/Credits/creditsData.ts
  modules/CreditsPage/index.tsx
  modules/CreditsPage/pages/CreditsPage.tsx
  modules/Login/pages/__snapshots__/Login.test.tsx.snap
  modules/shared/components/atoms/Avatar/Avatar.module.css
  modules/shared/components/atoms/Tab/Tab.module.css
  modules/shared/components/atoms/Tab/Tab.tsx
  modules/shared/components/atoms/Tab/__snapshots__/Tab.test.tsx.snap
  modules/shared/components/icons/deticatedRank.svg
  modules/shared/components/icons/github.svg
  modules/shared/components/icons/linkedin.svg
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.stories.tsx
  modules/shared/components/molecules/CreatePostHeader/CreatePostHeader.test.tsx
  modules/shared/components/molecules/CreatePostHeader/__snapshots__/CreatePostHeader.test.tsx.snap
  modules/shared/components/molecules/Footer/footerData.ts
  modules/shared/components/molecules/TabGroup/ITabGroup.d.ts
  modules/shared/components/molecules/TabGroup/TabGroup.stories.tsx
  modules/shared/components/molecules/TabGroup/TabGroup.test.tsx
  modules/shared/components/molecules/TabGroup/TabGroup.tsx
  modules/shared/components/molecules/TabGroup/data.tsx
  modules/shared/components/organisms/PostCreation/PostCreation.tsx
  modules/shared/components/organisms/PostCreation/types/EPollType.ts
  pages/_app.module.css
  pages/_app.tsx
  pages/credits/index.tsx
  public/Essam.jpeg
  public/hamada.png
  public/hawary.jpeg
  public/safei.jpg
  tailwind.config.js
Labels: under review, ready-for-review

#516 Fix post view and credits bug
  modules/CreditsPage/pages/CreditsPage.tsx
  modules/shared/components/organisms/SinglePostView/SinglePostView.tsx
Labels: ready-for-review

#518 Fix layout issues
  modules/shared/components/organisms/Modal/Modal.tsx
  modules/shared/components/organisms/Widgets/Widgets.module.css
  modules/shared/components/organisms/Widgets/Widgets.tsx
  pages/_app.module.css
  pages/_document.tsx
  styles/globals.css
Labels: ready-for-review

#511 Profile page content
  modules/HomePage/components/Posts/Posts.tsx
  modules/ProfilePage/api/IGetUserData.d.ts
  modules/ProfilePage/api/getUserData.ts
  modules/ProfilePage/api/profileMockedData.ts
  modules/ProfilePage/pages/ProfilePage.module.css
  modules/ProfilePage/pages/ProfilePage.tsx
  modules/shared/components/molecules/ImgWithInfo/IImgWithInfo.d.ts
  modules/shared/components/molecules/ImgWithInfo/ImgWithInfo.tsx
  modules/shared/components/molecules/Navigation/Navigation.tsx
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/molecules/TabGroup/data.tsx
  modules/shared/components/organisms/Widgets/Widgets.tsx
  modules/shared/hooks/useRedirect/IUseRedirect.d.ts
  modules/shared/hooks/useRedirect/useRedirect.ts
  pages/profile/[userid].tsx
Labels: ready-for-review

#522 Feedback integration with back end
  modules/shared/components/organisms/Feedback/Feedback.test.tsx
  modules/shared/components/organisms/Feedback/Feedback.tsx
  modules/shared/components/organisms/Feedback/api/IFeedbackApi.d.ts
  modules/shared/components/organisms/Feedback/api/feedbackApi.test.ts
  modules/shared/components/organisms/Feedback/api/feedbackApi.ts
  modules/shared/components/organisms/Feedback/api/feedbackHelpers.ts
Labels: ready-for-review

#520 Integrated with the back end to get a user data
  modules/HomePage/components/Posts/Posts.tsx
  modules/ProfilePage/api/getUserData.test.ts
  modules/ProfilePage/api/getUserData.ts
  modules/ProfilePage/api/getUserHelpers.ts
  modules/ProfilePage/api/profileMockedData.ts
  modules/ProfilePage/api/userData.ts
  modules/ProfilePage/pages/ProfilePage.tsx
  modules/shared/logic/formatDate/FormatDate.ts
  modules/shared/types/postFeed/IPostFeed.d.ts
  pages/profile/[userid].tsx
Labels: ready-for-review

#521 Report post api
  modules/HomePage/components/Posts/Posts.tsx
  modules/PostPage/PostPage.tsx
  modules/shared/api/EStatusCode.ts
  modules/shared/api/reportPost/IReportPostApi.d.ts
  modules/shared/api/reportPost/reportPost.test.ts
  modules/shared/api/reportPost/reportPostApi.ts
  modules/shared/api/reportPost/reportPostHelpers.ts
  modules/shared/components/molecules/PostViewHeader/IPostViewHeader.d.ts
  modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
  modules/shared/components/organisms/SinglePostView/ISinglePostView.d.ts
  modules/shared/components/organisms/SinglePostView/SinglePostView.tsx
Labels: ready-for-review

#523 Fix spaces in uncovered image option
  modules/shared/components/atoms/ImagePollCovered/ImagePollCovered.tsx
  modules/shared/components/atoms/ImagePollCovered/__snapshots__/ImagePollCovered.test.tsx.snap
  modules/shared/components/molecules/SingleImagePollOption/SingleImagePollOption.tsx
  modules/shared/components/molecules/SingleImagePollOption/__snapshots__/SingleImagePollOption.test.tsx.snap
  modules/shared/components/organisms/SinglePostView/SinglePostView.tsx
Labels: ready-for-review
