Repository m3ntorship/pickify-frontend, pull requests merged in 2021-05, with the labels that each got.

#21 Bugfix/tailwind css classes not working
  modules/articles/components/Heading/Heading.module.css
  modules/articles/components/Heading/index.tsx
  postcss.config.js
  tailwind.config.js
Labels: ready-for-review

#23 install postcss8 and postcss loader
  package.json
  yarn.lock
Labels: ready-for-review

#25 added react-test-renderer
  package.json
  yarn.lock
Labels: ready-for-review

#30 fix storybook
  .storybook/main.js
Labels: ready-for-review

#45 added needed colors for tailwind config
  tailwind.config.js
Labels: ready-for-review

#49 update tailwind values
  tailwind.config.js
Labels: ready-for-review

#53 svg loader
  .babelrc
  modules/shared/types/index.d.ts
  package.json
  yarn.lock
Labels: ready-for-review

#62 moved dependencies
  package.json
Labels: ready-for-review

#69 added tailwind values
  tailwind.config.js
Labels: ready-for-review

#68 Add global font-family "Roboto"
  pages/_app.tsx
  pages/_document.tsx
  styles/globals.css
  styles/typography.css
Labels: ready-for-review

#71 Text input component
  .eslintrc.js
  modules/example/components/example-one/index.stories.tsx
  modules/shared/components/atoms/TextInputs/TextInput.module.css
  modules/shared/components/atoms/TextInputs/TextInput.stories.tsx
  modules/shared/components/atoms/TextInputs/TextInput.test.tsx
  modules/shared/components/atoms/TextInputs/TextInput.tsx
  modules/shared/components/atoms/TextInputs/types/ETextInput.ts
  modules/shared/components/atoms/TextInputs/types/ITextInputs.d.ts
  modules/shared/components/icons/arrowDown.svg
  modules/shared/components/icons/imgTab.svg
  modules/shared/components/icons/inputArrowDown.svg
  modules/shared/components/icons/inputError.svg
  modules/shared/components/icons/inputFocus.svg
  modules/shared/components/icons/inputHome.svg
  modules/shared/components/icons/inputSuccess.svg
  pages/_app.tsx
  store/index.ts
  tailwind.config.js
Labels: ready-for-review

#77 tailwind config
  tailwind.config.js
Labels: ready-for-review

#61 created slider component
  modules/shared/components/atoms/Slider/ISlider.d.ts
  modules/shared/components/atoms/Slider/Slider.test.tsx
  modules/shared/components/atoms/Slider/__snapshots__/Slider.test.tsx.snap
  modules/shared/components/atoms/Slider/index.stories.tsx
  modules/shared/components/atoms/Slider/index.tsx
Labels: ready-for-review

#97 Tailwind break points
  tailwind.config.js
Labels: ready-for-review

#72 Checkbox component
  modules/shared/components/atoms/checkbox/CheckBox.module.css
  modules/shared/components/atoms/checkbox/CheckBox.test.tsx
  modules/shared/components/atoms/checkbox/__snapshots__/CheckBox.test.tsx.snap
  modules/shared/components/atoms/checkbox/index.stories.tsx
  modules/shared/components/atoms/checkbox/index.tsx
  modules/shared/components/atoms/checkbox/types/ECheckbox.ts
  modules/shared/components/atoms/checkbox/types/ICheckbox.d.ts
  modules/shared/components/icons/checkMarkDefault.svg
  modules/shared/components/icons/checkMarkSmall.svg
Labels: ready-for-review

#39 created avatar component
  .storybook/preview.js
  modules/articles/components/Heading/Heading.module.css
  modules/shared/components/atoms/avatar/Avatar.module.css
  modules/shared/components/atoms/avatar/Avatar.stories.tsx
  modules/shared/components/atoms/avatar/Avatar.tsx
  modules/shared/components/atoms/avatar/Avatart.test.tsx
  modules/shared/components/atoms/avatar/IAvatar.d.ts
  modules/shared/components/icons/anonymous.svg
  modules/shared/components/icons/notFilled.svg
  next.config.js
  package.json
  tailwind.config.js
Labels: ready-for-review

#64 created the button component
  modules/shared/components/atoms/Button/Button.module.css
  modules/shared/components/atoms/Button/Button.test.tsx
  modules/shared/components/atoms/Button/__snapshots__/Button.test.tsx.snap
  modules/shared/components/atoms/Button/index.stories.tsx
  modules/shared/components/atoms/Button/index.tsx
  modules/shared/components/atoms/Button/types/EButton.ts
  modules/shared/components/atoms/Button/types/IButton.d.ts
  modules/shared/components/icons/buttonArowDown.svg
Labels: ready-for-review, under review

#63 Readme Update
  README.md
Labels: documentation, ready-for-review

#105 Radio changes
  modules/shared/components/atoms/Radio/IRadio.d.ts
  modules/shared/components/atoms/Radio/Radio.module.css
  modules/shared/components/atoms/Radio/Radio.test.tsx
  modules/shared/components/atoms/Radio/__snapshots__/Radio.test.tsx.snap
  modules/shared/components/atoms/Radio/index.tsx
Labels: ready-for-review

#94 install identity-obj-proxy to map css module
  jest.config.js
  modules/articles/components/Heading/Heading.test.tsx
  modules/articles/components/Heading/IHeading.d.ts
  modules/articles/components/Heading/__snapshots__/Heading.test.tsx.snap
  modules/articles/components/Heading/index.stories.tsx
  modules/articles/components/Heading/index.tsx
  modules/shared/components/atoms/Button/__snapshots__/Button.test.tsx.snap
  modules/shared/components/atoms/Button/index.tsx
  modules/shared/components/atoms/Radio/__snapshots__/Radio.test.tsx.snap
  modules/shared/components/atoms/Slider/index.tsx
  modules/shared/components/atoms/avatar/Avatar.tsx
  modules/shared/components/atoms/avatar/__snapshots__/Avatart.test.tsx.snap
  modules/shared/components/atoms/checkbox/__snapshots__/CheckBox.test.tsx.snap
  modules/shared/components/atoms/checkbox/index.tsx
  modules/shared/components/atoms/toggler/__snapshots__/toggler.test.tsx.snap
  modules/shared/components/atoms/toggler/toggler.test.tsx
  package.json
  yarn.lock
Labels: bug, ready-for-review

#111 Created votes logic
  modules/shared/logic/votesLogic/votesLogic.test.ts
  modules/shared/logic/votesLogic/votesLogic.ts
Labels: ready-for-review

#106 added UserInfo component
  modules/shared/components/molecules/UserInfo/IUserInfo.d.ts
  modules/shared/components/molecules/UserInfo/Index.tsx
  modules/shared/components/molecules/UserInfo/UserInfo.module.css
  modules/shared/components/molecules/UserInfo/UserInfo.stories.tsx
  modules/shared/components/molecules/UserInfo/UserInfo.test.tsx
Labels: ready-for-review

#112 Textpoll component
  modules/shared/components/atoms/textPoll/ITextPoll.d.ts
  modules/shared/components/atoms/textPoll/TextPoll.module.css
  modules/shared/components/atoms/textPoll/TextPoll.stories.tsx
  modules/shared/components/atoms/textPoll/TextPoll.test.tsx
  modules/shared/components/atoms/textPoll/__snapshots__/TextPoll.test.tsx.snap
  modules/shared/components/atoms/textPoll/index.tsx
  modules/shared/components/icons/checkMarkDefault.svg
  modules/shared/components/icons/goldenStar.svg
  tailwind.config.js
Labels: ready-for-merge

#114 Feature/divider
  modules/shared/components/atoms/Divider/Divider.stories.tsx
  modules/shared/components/atoms/Divider/Divider.test.tsx
  modules/shared/components/atoms/Divider/Divider.tsx
  modules/shared/components/atoms/Divider/__snapshots__/Divider.test.tsx.snap
  modules/shared/components/atoms/Divider/types/EDivider.ts
  modules/shared/components/atoms/Divider/types/IDivider.d.ts
Labels: ready-for-review

#115 Create footer of the post
  modules/shared/components/icons/share.svg
  modules/shared/components/molecules/postFooter/IPostFooter.d.ts
  modules/shared/components/molecules/postFooter/PostFooter.module.css
  modules/shared/components/molecules/postFooter/PostFooter.stories.tsx
  modules/shared/components/molecules/postFooter/PostFooter.test.tsx
  modules/shared/components/molecules/postFooter/PostFooter.tsx
  modules/shared/components/molecules/postFooter/__snapshots__/PostFooter.test.tsx.snap
Labels: ready-for-review, under review
